// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHV_KhBfe1pr14LP3-qhyldpEYmBNqKak',
    appId: '1:645865522137:web:8fda2da4238c5f72ad8fc8',
    messagingSenderId: '645865522137',
    projectId: 'programobil2860',
    authDomain: 'programobil2860.firebaseapp.com',
    storageBucket: 'programobil2860.firebasestorage.app',
    measurementId: 'G-WXZ4PR4VK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RF4QdqyV0jFhIDKLVZI4ec8vOOKfI00',
    appId: '1:645865522137:android:7678c38be8168102ad8fc8',
    messagingSenderId: '645865522137',
    projectId: 'programobil2860',
    storageBucket: 'programobil2860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOCX3PrtwSUDYSyOIPuaA5WLGNztegj7k',
    appId: '1:645865522137:ios:134aa5f790197812ad8fc8',
    messagingSenderId: '645865522137',
    projectId: 'programobil2860',
    storageBucket: 'programobil2860.firebasestorage.app',
    iosBundleId: 'com.example.paginaMuestra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOCX3PrtwSUDYSyOIPuaA5WLGNztegj7k',
    appId: '1:645865522137:ios:134aa5f790197812ad8fc8',
    messagingSenderId: '645865522137',
    projectId: 'programobil2860',
    storageBucket: 'programobil2860.firebasestorage.app',
    iosBundleId: 'com.example.paginaMuestra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHV_KhBfe1pr14LP3-qhyldpEYmBNqKak',
    appId: '1:645865522137:web:8a0875671b7e55daad8fc8',
    messagingSenderId: '645865522137',
    projectId: 'programobil2860',
    authDomain: 'programobil2860.firebaseapp.com',
    storageBucket: 'programobil2860.firebasestorage.app',
    measurementId: 'G-VC470X2L0M',
  );
}
